import { useTranslations } from 'next-intl'
import { type StepsCollection } from './steps'

export function useLocalizedSteps(): StepsCollection {
  const t = useTranslations('steps')

  return {
    PLAN_INFORMATION: {
      title: t('planInformation.title'),
      description: t('planInformation.description'),
      inputs: [
        {
          type: 'text',
          label: t('planInformation.inputs.companyName.label'),
          required: true,
          prompt: t('planInformation.inputs.companyName.prompt'),
          examples: [
            t('planInformation.inputs.companyName.examples.0'),
            t('planInformation.inputs.companyName.examples.1'),
            t('planInformation.inputs.companyName.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.businessAddress.label'),
          required: true,
          prompt: t('planInformation.inputs.businessAddress.prompt'),
          examples: [
            t('planInformation.inputs.businessAddress.examples.0'),
            t('planInformation.inputs.businessAddress.examples.1'),
            t('planInformation.inputs.businessAddress.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.planManager.label'),
          required: true,
          prompt: t('planInformation.inputs.planManager.prompt'),
          examples: [
            t('planInformation.inputs.planManager.examples.0'),
            t('planInformation.inputs.planManager.examples.1'),
            t('planInformation.inputs.planManager.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.alternateManager.label'),
          required: false,
          prompt: t('planInformation.inputs.alternateManager.prompt'),
          examples: [
            t('planInformation.inputs.alternateManager.examples.0'),
            t('planInformation.inputs.alternateManager.examples.1'),
            t('planInformation.inputs.alternateManager.examples.2'),
            t('planInformation.inputs.alternateManager.examples.3'),
            t('planInformation.inputs.alternateManager.examples.4'),
            t('planInformation.inputs.alternateManager.examples.5'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.physicalPlanLocation.label'),
          required: true,
          prompt: t('planInformation.inputs.physicalPlanLocation.prompt'),
          examples: [
            t('planInformation.inputs.physicalPlanLocation.examples.0'),
            t('planInformation.inputs.physicalPlanLocation.examples.1'),
            t('planInformation.inputs.physicalPlanLocation.examples.2'),
            t('planInformation.inputs.physicalPlanLocation.examples.3'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.digitalPlanLocation.label'),
          required: false,
          prompt: t('planInformation.inputs.digitalPlanLocation.prompt'),
          examples: [
            t('planInformation.inputs.digitalPlanLocation.examples.0'),
            t('planInformation.inputs.digitalPlanLocation.examples.1'),
            t('planInformation.inputs.digitalPlanLocation.examples.2'),
            t('planInformation.inputs.digitalPlanLocation.examples.3'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.planVersion.label'),
          required: true,
          prompt: t('planInformation.inputs.planVersion.prompt'),
          examples: [
            t('planInformation.inputs.planVersion.examples.0'),
            t('planInformation.inputs.planVersion.examples.1'),
            t('planInformation.inputs.planVersion.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('planInformation.inputs.nextReviewDate.label'),
          required: true,
          prompt: t('planInformation.inputs.nextReviewDate.prompt'),
          examples: [
            t('planInformation.inputs.nextReviewDate.examples.0'),
            t('planInformation.inputs.nextReviewDate.examples.1'),
            t('planInformation.inputs.nextReviewDate.examples.2'),
          ],
        },
      ],
    },

    BUSINESS_OVERVIEW: {
      title: t('businessOverview.title'),
      description: t('businessOverview.description'),
      inputs: [
        {
          type: 'text',
          label: t('businessOverview.inputs.businessLicense.label'),
          required: true,
          prompt: t('businessOverview.inputs.businessLicense.prompt'),
          examples: [
            t('businessOverview.inputs.businessLicense.examples.0'),
            t('businessOverview.inputs.businessLicense.examples.1'),
            t('businessOverview.inputs.businessLicense.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.businessPurpose.label'),
          required: true,
          prompt: t('businessOverview.inputs.businessPurpose.prompt'),
          examples: [
            t('businessOverview.inputs.businessPurpose.examples.0'),
            t('businessOverview.inputs.businessPurpose.examples.1'),
            t('businessOverview.inputs.businessPurpose.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.productsAndServices.label'),
          required: true,
          prompt: t('businessOverview.inputs.productsAndServices.prompt'),
          examples: [
            t('businessOverview.inputs.productsAndServices.examples.0'),
            t('businessOverview.inputs.productsAndServices.examples.1'),
            t('businessOverview.inputs.productsAndServices.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.serviceDeliveryMethods.label'),
          required: true,
          prompt: t('businessOverview.inputs.serviceDeliveryMethods.prompt'),
          examples: [
            t('businessOverview.inputs.serviceDeliveryMethods.examples.0'),
            t('businessOverview.inputs.serviceDeliveryMethods.examples.1'),
            t('businessOverview.inputs.serviceDeliveryMethods.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.operatingHours.label'),
          required: true,
          prompt: t('businessOverview.inputs.operatingHours.prompt'),
          examples: [
            t('businessOverview.inputs.operatingHours.examples.0'),
            t('businessOverview.inputs.operatingHours.examples.1'),
            t('businessOverview.inputs.operatingHours.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.keyPersonnel.label'),
          required: true,
          prompt: t('businessOverview.inputs.keyPersonnel.prompt'),
          examples: [
            t('businessOverview.inputs.keyPersonnel.examples.0'),
            t('businessOverview.inputs.keyPersonnel.examples.1'),
            t('businessOverview.inputs.keyPersonnel.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.minimumResources.label'),
          required: true,
          prompt: t('businessOverview.inputs.minimumResources.prompt'),
          examples: [
            t('businessOverview.inputs.minimumResources.examples.0'),
            t('businessOverview.inputs.minimumResources.examples.1'),
            t('businessOverview.inputs.minimumResources.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('businessOverview.inputs.customerBase.label'),
          required: true,
          prompt: t('businessOverview.inputs.customerBase.prompt'),
          examples: [
            t('businessOverview.inputs.customerBase.examples.0'),
            t('businessOverview.inputs.customerBase.examples.1'),
            t('businessOverview.inputs.customerBase.examples.2'),
          ],
        },
        {
          type: 'radio',
          label: 'Approximate Annual Revenue',
          required: false,
          prompt: 'What is your approximate annual revenue? Select the range that best fits your business. This helps demonstrate your business size for loan applications and insurance renewals.',
          options: [
            { label: 'Under 1 million', value: 'under_1m' },
            { label: '1-3 million', value: '1m_3m' },
            { label: '3-10 million', value: '3m_10m' },
            { label: '10-20 million', value: '10m_20m' },
            { label: 'Over 20 million', value: 'over_20m' },
            { label: 'Prefer not to disclose', value: 'not_disclosed' },
          ],
        },
        {
          type: 'radio',
          label: 'Total People in Business',
          required: false,
          prompt: 'How many people work in your business in total? Include yourself, family members, full-time staff, part-time staff, and regular contractors.',
          options: [
            { label: 'Just me (1 person)', value: '1' },
            { label: '2-5 people', value: '2-5' },
            { label: '6-10 people', value: '6-10' },
            { label: '11-25 people', value: '11-25' },
            { label: '26-50 people', value: '26-50' },
            { label: 'More than 50 people', value: '50+' },
          ],
        },
        {
          type: 'radio',
          label: 'Years in Operation',
          required: false,
          prompt: 'How long has your business been operating? This helps demonstrate your experience and track record.',
          options: [
            { label: 'Less than 1 year (just starting)', value: '0-1' },
            { label: '1-2 years', value: '1-2' },
            { label: '3-5 years', value: '3-5' },
            { label: '6-10 years', value: '6-10' },
            { label: '11-20 years', value: '11-20' },
            { label: 'More than 20 years', value: '20+' },
          ],
        },
        {
          type: 'radio',
          label: t('businessOverview.inputs.serviceProviderBCP.label'),
          required: true,
          prompt: t('businessOverview.inputs.serviceProviderBCP.prompt'),
          options: [
            { label: t('businessOverview.inputs.serviceProviderBCP.options.0.label'), value: 'yes' },
            { label: t('businessOverview.inputs.serviceProviderBCP.options.1.label'), value: 'no' },
            { label: t('businessOverview.inputs.serviceProviderBCP.options.2.label'), value: 'partial' },
            { label: t('businessOverview.inputs.serviceProviderBCP.options.3.label'), value: 'unknown' },
          ],
        },
      ],
    },

    ESSENTIAL_FUNCTIONS: {
      title: t('essentialFunctions.title'),
      description: t('essentialFunctions.description'),
      inputs: [
        {
          type: 'table',
          label: t('essentialFunctions.inputs.businessFunctions.label'),
          required: true,
          prompt: t('essentialFunctions.inputs.businessFunctions.prompt'),
          tableColumns: [
            t('essentialFunctions.inputs.businessFunctions.tableColumns.0'),
            t('essentialFunctions.inputs.businessFunctions.tableColumns.1'),
            t('essentialFunctions.inputs.businessFunctions.tableColumns.2'),
            t('essentialFunctions.inputs.businessFunctions.tableColumns.3'),
            t('essentialFunctions.inputs.businessFunctions.tableColumns.4'),
          ],
          tableRowsPrompt: t('essentialFunctions.inputs.businessFunctions.tableRowsPromptPartial'),
          priorityOptions: [
            { label: t('essentialFunctions.inputs.businessFunctions.priorityOptions.0.label'), value: 'critical' },
            { label: t('essentialFunctions.inputs.businessFunctions.priorityOptions.1.label'), value: 'important' },
            { label: t('essentialFunctions.inputs.businessFunctions.priorityOptions.2.label'), value: 'useful' },
            { label: t('essentialFunctions.inputs.businessFunctions.priorityOptions.3.label'), value: 'deferrable' },
          ],
          downtimeOptions: [
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.0.label'), value: '0-2h' },
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.1.label'), value: '2-8h' },
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.2.label'), value: '8-24h' },
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.3.label'), value: '1-3d' },
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.4.label'), value: '3-7d' },
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.5.label'), value: '1-2w' },
            { label: t('essentialFunctions.inputs.businessFunctions.downtimeOptions.6.label'), value: '2w+' },
          ],
          examples: [
            t('essentialFunctions.inputs.businessFunctions.examples.0'),
            t('essentialFunctions.inputs.businessFunctions.examples.1'),
            t('essentialFunctions.inputs.businessFunctions.examples.2'),
          ],
        },
      ],
    },

    RISK_ASSESSMENT: {
      title: t('riskAssessment.title'),
      description: t('riskAssessment.description'),
      inputs: [
        {
          type: 'special_risk_matrix',
          label: t('riskAssessment.inputs.riskMatrix.label'),
          prompt: t('riskAssessment.inputs.riskMatrix.prompt'),
          required: true,
          examples: [
            t('riskAssessment.inputs.riskMatrix.examples.0'),
            t('riskAssessment.inputs.riskMatrix.examples.1'),
            t('riskAssessment.inputs.riskMatrix.examples.2'),
          ],
        },
      ],
    },

    STRATEGIES: {
      title: t('strategies.title'),
      description: t('strategies.description'),
      inputs: [
        {
          type: 'special_strategy_cards',
          label: t('strategies.title'),
          required: true,
          prompt: t('strategySelection.selectStrategiesDescription'),
          examples: [
            t('strategies.examples.autoRecommended'),
            t('strategies.examples.prevention'),
            t('strategies.examples.response'),
            t('strategies.examples.recovery')
          ],
        },
      ],
    },

    CONTACTS_AND_INFORMATION: {
      title: t('contactsAndInformation.title'),
      description: t('contactsAndInformation.description'),
      inputs: [
        {
          type: 'table',
          label: t('contactsAndInformation.inputs.staffContacts.label'),
          prompt: t('contactsAndInformation.inputs.staffContacts.prompt'),
          required: true,
          tableColumns: [
            t('contactsAndInformation.inputs.staffContacts.tableColumns.0'),
            t('contactsAndInformation.inputs.staffContacts.tableColumns.1'),
            t('contactsAndInformation.inputs.staffContacts.tableColumns.2'),
            t('contactsAndInformation.inputs.staffContacts.tableColumns.3'),
            t('contactsAndInformation.inputs.staffContacts.tableColumns.4'),
          ],
          tableRowsPrompt: t('contactsAndInformation.inputs.staffContacts.tableRowsPrompt'),
          examples: [
            t('contactsAndInformation.inputs.staffContacts.examples.0'),
            t('contactsAndInformation.inputs.staffContacts.examples.1'),
            t('contactsAndInformation.inputs.staffContacts.examples.2'),
          ],
        },
        {
          type: 'table',
          label: t('contactsAndInformation.inputs.keyCustomers.label'),
          prompt: t('contactsAndInformation.inputs.keyCustomers.prompt'),
          required: false,
          tableColumns: [
            t('contactsAndInformation.inputs.keyCustomers.tableColumns.0'),
            t('contactsAndInformation.inputs.keyCustomers.tableColumns.1'),
            t('contactsAndInformation.inputs.keyCustomers.tableColumns.2'),
            t('contactsAndInformation.inputs.keyCustomers.tableColumns.3'),
            t('contactsAndInformation.inputs.keyCustomers.tableColumns.4'),
          ],
          tableRowsPrompt: t('contactsAndInformation.inputs.keyCustomers.tableRowsPrompt'),
          examples: [
            t('contactsAndInformation.inputs.keyCustomers.examples.0'),
            t('contactsAndInformation.inputs.keyCustomers.examples.1'),
            t('contactsAndInformation.inputs.keyCustomers.examples.2'),
          ],
        },
        {
          type: 'table',
          label: t('contactsAndInformation.inputs.supplierInfo.label'),
          prompt: t('contactsAndInformation.inputs.supplierInfo.prompt'),
          required: true,
          tableColumns: [
            t('contactsAndInformation.inputs.supplierInfo.tableColumns.0'),
            t('contactsAndInformation.inputs.supplierInfo.tableColumns.1'),
            t('contactsAndInformation.inputs.supplierInfo.tableColumns.2'),
            t('contactsAndInformation.inputs.supplierInfo.tableColumns.3'),
            t('contactsAndInformation.inputs.supplierInfo.tableColumns.4'),
          ],
          tableRowsPrompt: t('contactsAndInformation.inputs.supplierInfo.tableRowsPrompt'),
          examples: [
            t('contactsAndInformation.inputs.supplierInfo.examples.0'),
            t('contactsAndInformation.inputs.supplierInfo.examples.1'),
            t('contactsAndInformation.inputs.supplierInfo.examples.2'),
          ],
        },
        {
          type: 'table',
          label: t('contactsAndInformation.inputs.emergencyServices.label'),
          prompt: t('contactsAndInformation.inputs.emergencyServices.prompt'),
          required: true,
          tableColumns: [
            t('contactsAndInformation.inputs.emergencyServices.tableColumns.0'),
            t('contactsAndInformation.inputs.emergencyServices.tableColumns.1'),
            t('contactsAndInformation.inputs.emergencyServices.tableColumns.2'),
            t('contactsAndInformation.inputs.emergencyServices.tableColumns.3'),
            t('contactsAndInformation.inputs.emergencyServices.tableColumns.4'),
          ],
          tableRowsPrompt: t('contactsAndInformation.inputs.emergencyServices.tableRowsPrompt'),
          examples: [
            t('contactsAndInformation.inputs.emergencyServices.examples.0'),
            t('contactsAndInformation.inputs.emergencyServices.examples.1'),
            t('contactsAndInformation.inputs.emergencyServices.examples.2'),
            t('contactsAndInformation.inputs.emergencyServices.examples.3'),
            t('contactsAndInformation.inputs.emergencyServices.examples.4'),
            t('contactsAndInformation.inputs.emergencyServices.examples.5'),
          ],
        },
        {
          type: 'text',
          label: t('contactsAndInformation.inputs.criticalBusinessInfo.label'),
          required: true,
          prompt: t('contactsAndInformation.inputs.criticalBusinessInfo.prompt'),
          examples: [
            t('contactsAndInformation.inputs.criticalBusinessInfo.examples.0'),
            t('contactsAndInformation.inputs.criticalBusinessInfo.examples.1'),
          ],
        },
        {
          type: 'table',
          label: t('contactsAndInformation.inputs.planDistribution.label'),
          prompt: t('contactsAndInformation.inputs.planDistribution.prompt'),
          required: true,
          tableColumns: [
            t('contactsAndInformation.inputs.planDistribution.tableColumns.0'),
            t('contactsAndInformation.inputs.planDistribution.tableColumns.1'),
            t('contactsAndInformation.inputs.planDistribution.tableColumns.2'),
            t('contactsAndInformation.inputs.planDistribution.tableColumns.3'),
            t('contactsAndInformation.inputs.planDistribution.tableColumns.4'),
          ],
          tableRowsPrompt: t('contactsAndInformation.inputs.planDistribution.tableRowsPrompt'),
          examples: [
            t('contactsAndInformation.inputs.planDistribution.examples.0'),
            t('contactsAndInformation.inputs.planDistribution.examples.1'),
            t('contactsAndInformation.inputs.planDistribution.examples.2'),
          ],
        },
      ],
    },

    VITAL_RECORDS: {
      title: t('vitalRecords.title'),
      description: t('vitalRecords.description'),
      inputs: [
        {
          type: 'table',
          label: t('vitalRecords.inputs.vitalRecordsInventory.label'),
          prompt: t('vitalRecords.inputs.vitalRecordsInventory.prompt'),
          required: true,
          tableColumns: [
            t('vitalRecords.inputs.vitalRecordsInventory.tableColumns.0'),
            t('vitalRecords.inputs.vitalRecordsInventory.tableColumns.1'),
            t('vitalRecords.inputs.vitalRecordsInventory.tableColumns.2'),
            t('vitalRecords.inputs.vitalRecordsInventory.tableColumns.3'),
          ],
          tableRowsPrompt: t('vitalRecords.inputs.vitalRecordsInventory.tableRowsPrompt'),
          examples: [
            t('vitalRecords.inputs.vitalRecordsInventory.examples.0'),
            t('vitalRecords.inputs.vitalRecordsInventory.examples.1'),
            t('vitalRecords.inputs.vitalRecordsInventory.examples.2'),
            t('vitalRecords.inputs.vitalRecordsInventory.examples.3'),
            t('vitalRecords.inputs.vitalRecordsInventory.examples.4'),
          ],
        },
      ],
    },

    TESTING_AND_MAINTENANCE: {
      title: t('testingAndMaintenance.title'),
      description: t('testingAndMaintenance.description'),
      inputs: [
        {
          type: 'table',
          label: t('testingAndMaintenance.inputs.testingSchedule.label'),
          prompt: t('testingAndMaintenance.inputs.testingSchedule.prompt'),
          required: true,
          tableColumns: [
            t('testingAndMaintenance.inputs.testingSchedule.tableColumns.0'),
            t('testingAndMaintenance.inputs.testingSchedule.tableColumns.1'),
            t('testingAndMaintenance.inputs.testingSchedule.tableColumns.2'),
            t('testingAndMaintenance.inputs.testingSchedule.tableColumns.3'),
            t('testingAndMaintenance.inputs.testingSchedule.tableColumns.4'),
            t('testingAndMaintenance.inputs.testingSchedule.tableColumns.5'),
          ],
          tableRowsPrompt: t('testingAndMaintenance.inputs.testingSchedule.tableRowsPrompt'),
          examples: [
            t('testingAndMaintenance.inputs.testingSchedule.examples.0'),
            t('testingAndMaintenance.inputs.testingSchedule.examples.1'),
            t('testingAndMaintenance.inputs.testingSchedule.examples.2'),
            t('testingAndMaintenance.inputs.testingSchedule.examples.3'),
            t('testingAndMaintenance.inputs.testingSchedule.examples.4'),
            t('testingAndMaintenance.inputs.testingSchedule.examples.5'),
          ],
        },
        {
          type: 'table',
          label: t('testingAndMaintenance.inputs.trainingSchedule.label'),
          prompt: t('testingAndMaintenance.inputs.trainingSchedule.prompt'),
          required: true,
          tableColumns: [
            t('testingAndMaintenance.inputs.trainingSchedule.tableColumns.0'),
            t('testingAndMaintenance.inputs.trainingSchedule.tableColumns.1'),
            t('testingAndMaintenance.inputs.trainingSchedule.tableColumns.2'),
            t('testingAndMaintenance.inputs.trainingSchedule.tableColumns.3'),
            t('testingAndMaintenance.inputs.trainingSchedule.tableColumns.4'),
            t('testingAndMaintenance.inputs.trainingSchedule.tableColumns.5'),
          ],
          tableRowsPrompt: t('testingAndMaintenance.inputs.trainingSchedule.tableRowsPrompt'),
          examples: [
            t('testingAndMaintenance.inputs.trainingSchedule.examples.0'),
            t('testingAndMaintenance.inputs.trainingSchedule.examples.1'),
            t('testingAndMaintenance.inputs.trainingSchedule.examples.2'),
            t('testingAndMaintenance.inputs.trainingSchedule.examples.3'),
            t('testingAndMaintenance.inputs.trainingSchedule.examples.4'),
          ],
        },
        {
          type: 'table',
          label: t('testingAndMaintenance.inputs.performanceMetrics.label'),
          prompt: t('testingAndMaintenance.inputs.performanceMetrics.prompt'),
          required: true,
          tableColumns: [
            t('testingAndMaintenance.inputs.performanceMetrics.tableColumns.0'),
            t('testingAndMaintenance.inputs.performanceMetrics.tableColumns.1'),
            t('testingAndMaintenance.inputs.performanceMetrics.tableColumns.2'),
            t('testingAndMaintenance.inputs.performanceMetrics.tableColumns.3'),
            t('testingAndMaintenance.inputs.performanceMetrics.tableColumns.4'),
            t('testingAndMaintenance.inputs.performanceMetrics.tableColumns.5'),
          ],
          tableRowsPrompt: t('testingAndMaintenance.inputs.performanceMetrics.tableRowsPrompt'),
          examples: [
            t('testingAndMaintenance.inputs.performanceMetrics.examples.0'),
            t('testingAndMaintenance.inputs.performanceMetrics.examples.1'),
            t('testingAndMaintenance.inputs.performanceMetrics.examples.2'),
            t('testingAndMaintenance.inputs.performanceMetrics.examples.3'),
            t('testingAndMaintenance.inputs.performanceMetrics.examples.4'),
          ],
        },
        {
          type: 'table',
          label: t('testingAndMaintenance.inputs.revisionHistory.label'),
          prompt: t('testingAndMaintenance.inputs.revisionHistory.prompt'),
          required: true,
          tableColumns: [
            t('testingAndMaintenance.inputs.revisionHistory.tableColumns.0'),
            t('testingAndMaintenance.inputs.revisionHistory.tableColumns.1'),
            t('testingAndMaintenance.inputs.revisionHistory.tableColumns.2'),
            t('testingAndMaintenance.inputs.revisionHistory.tableColumns.3'),
            t('testingAndMaintenance.inputs.revisionHistory.tableColumns.4'),
          ],
          tableRowsPrompt: t('testingAndMaintenance.inputs.revisionHistory.tableRowsPrompt'),
          examples: [
            t('testingAndMaintenance.inputs.revisionHistory.examples.0'),
            t('testingAndMaintenance.inputs.revisionHistory.examples.1'),
            t('testingAndMaintenance.inputs.revisionHistory.examples.2'),
          ],
        },
        {
          type: 'table',
          label: t('testingAndMaintenance.inputs.improvementTracking.label'),
          prompt: t('testingAndMaintenance.inputs.improvementTracking.prompt'),
          required: true,
          tableColumns: [
            t('testingAndMaintenance.inputs.improvementTracking.tableColumns.0'),
            t('testingAndMaintenance.inputs.improvementTracking.tableColumns.1'),
            t('testingAndMaintenance.inputs.improvementTracking.tableColumns.2'),
            t('testingAndMaintenance.inputs.improvementTracking.tableColumns.3'),
            t('testingAndMaintenance.inputs.improvementTracking.tableColumns.4'),
          ],
          tableRowsPrompt: t('testingAndMaintenance.inputs.improvementTracking.tableRowsPrompt'),
          examples: [
            t('testingAndMaintenance.inputs.improvementTracking.examples.0'),
            t('testingAndMaintenance.inputs.improvementTracking.examples.1'),
            t('testingAndMaintenance.inputs.improvementTracking.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('testingAndMaintenance.inputs.annualReview.label'),
          required: true,
          prompt: t('testingAndMaintenance.inputs.annualReview.prompt'),
          examples: [
            t('testingAndMaintenance.inputs.annualReview.examples.0'),
            t('testingAndMaintenance.inputs.annualReview.examples.1'),
            t('testingAndMaintenance.inputs.annualReview.examples.2'),
          ],
        },
        {
          type: 'text',
          label: t('testingAndMaintenance.inputs.triggerEvents.label'),
          required: true,
          prompt: t('testingAndMaintenance.inputs.triggerEvents.prompt'),
          examples: [
            t('testingAndMaintenance.inputs.triggerEvents.examples.0'),
            t('testingAndMaintenance.inputs.triggerEvents.examples.1'),
            t('testingAndMaintenance.inputs.triggerEvents.examples.2'),
          ],
        },
      ],
    },
  }
} 